version: '3.8'
services:
  fastapi:
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: >
      bash -c "echo 'Waiting for database...' &&
               python init_db.py &&
               echo 'Starting FastAPI application in development mode...' &&
               uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  
  frontend:
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next 