version: '3.8'
services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://pm_user:pm_password@pm_postgres_db:5432/pm_database
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: >
      bash -c "
      echo 'Waiting for database...' &&
      sleep 10 &&
      echo 'Starting FastAPI application in development mode...' &&
      uvicorn main:app --host 0.0.0.0 --port 8000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key-change-in-production
      - BACKEND_URL=http://fastapi:8000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - nextjs_cache:/app/.next/cache
    # Remove the user override to let the Dockerfile handle it
    # user: "1001:1001"  # Comment this out
    command: >
      sh -c "
      # Fix permissions for mounted volumes
      sudo chown -R nextjs:nodejs /app &&
      sudo chmod -R 775 /app &&
      # Ensure Next.js directories exist with correct permissions
      mkdir -p .next .next/cache .next/server .next/static &&
      touch next-env.d.ts &&
      npm run dev"

volumes:
  nextjs_cache:
