version: '3.8'

services:
  frontend:
    depends_on:
      # Temporarily removed fastapi dependency due to database auth issues
      # fastapi:
      #   condition: service_healthy

  nginx:
    depends_on:
      # Temporarily removed fastapi dependency due to database auth issues
      # fastapi:
      #   condition: service_healthy
      frontend:
        condition: service_healthy
