"""Add jobs and topics with many-to-many relationships

Revision ID: 48b08dc0ffc8
Revises: 
Create Date: 2025-07-24 10:40:29.507041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b08dc0ffc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='jobstatus'), nullable=False),
    sa.Column('before_image', sa.String(length=500), nullable=True),
    sa.Column('after_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_created_date', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_job_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_job_title_status', 'jobs', ['title', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('job_properties',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'property_id')
    )
    op.create_index('idx_job_property_job', 'job_properties', ['job_id'], unique=False)
    op.create_index('idx_job_property_property', 'job_properties', ['property_id'], unique=False)
    op.create_table('job_topics',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'topic_id')
    )
    op.create_index('idx_job_topic_job', 'job_topics', ['job_id'], unique=False)
    op.create_index('idx_job_topic_topic', 'job_topics', ['topic_id'], unique=False)
    op.create_table('job_users',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'user_id')
    )
    op.create_index('idx_job_user_job', 'job_users', ['job_id'], unique=False)
    op.create_index('idx_job_user_user', 'job_users', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('PM_DUE', 'PM_OVERDUE', 'ISSUE_CREATED', 'ISSUE_ASSIGNED', 'INSPECTION_DUE', 'SYSTEM_ALERT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_entity', 'notifications', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_index('idx_notification_type_date', 'notifications', ['notification_type', 'created_at'], unique=False)
    op.create_index('idx_notification_unread', 'notifications', ['is_read', 'created_at'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_type'), 'notifications', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_title'), 'notifications', ['title'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('job_rooms',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'room_id')
    )
    op.create_index('idx_job_room_job', 'job_rooms', ['job_id'], unique=False)
    op.create_index('idx_job_room_room', 'job_rooms', ['room_id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('labor_hours', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_log_cost_date', 'maintenance_logs', ['cost', 'performed_at'], unique=False)
    op.create_index('idx_maintenance_log_machine_date', 'maintenance_logs', ['machine_id', 'performed_at'], unique=False)
    op.create_index('idx_maintenance_log_type_date', 'maintenance_logs', ['log_type', 'performed_at'], unique=False)
    op.create_index('idx_maintenance_log_user_date', 'maintenance_logs', ['user_id', 'performed_at'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_cost'), 'maintenance_logs', ['cost'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_created_at'), 'maintenance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_labor_hours'), 'maintenance_logs', ['labor_hours'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_log_type'), 'maintenance_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_machine_id'), 'maintenance_logs', ['machine_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_performed_at'), 'maintenance_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_title'), 'maintenance_logs', ['title'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_user_id'), 'maintenance_logs', ['user_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('work_order_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION', name='workordertype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cost_estimate', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_order_assigned_status', 'work_orders', ['assigned_to_id', 'status'], unique=False)
    op.create_index('idx_work_order_completed_date', 'work_orders', ['completed_at', 'status'], unique=False)
    op.create_index('idx_work_order_created_date', 'work_orders', ['created_at', 'work_order_type'], unique=False)
    op.create_index('idx_work_order_machine_status', 'work_orders', ['machine_id', 'status'], unique=False)
    op.create_index('idx_work_order_priority_status', 'work_orders', ['priority', 'status'], unique=False)
    op.create_index('idx_work_order_scheduled_date', 'work_orders', ['scheduled_date', 'status'], unique=False)
    op.create_index('idx_work_order_status_type', 'work_orders', ['status', 'work_order_type'], unique=False)
    op.create_index(op.f('ix_work_orders_actual_cost'), 'work_orders', ['actual_cost'], unique=False)
    op.create_index(op.f('ix_work_orders_actual_hours'), 'work_orders', ['actual_hours'], unique=False)
    op.create_index(op.f('ix_work_orders_assigned_to_id'), 'work_orders', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_work_orders_completed_at'), 'work_orders', ['completed_at'], unique=False)
    op.create_index(op.f('ix_work_orders_cost_estimate'), 'work_orders', ['cost_estimate'], unique=False)
    op.create_index(op.f('ix_work_orders_created_at'), 'work_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_orders_created_by_id'), 'work_orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_work_orders_estimated_hours'), 'work_orders', ['estimated_hours'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_is_active'), 'work_orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_orders_machine_id'), 'work_orders', ['machine_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_scheduled_date'), 'work_orders', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_work_orders_started_at'), 'work_orders', ['started_at'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_title'), 'work_orders', ['title'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_type'), 'work_orders', ['work_order_type'], unique=False)
    op.add_column('machines', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('machine_type', sa.Enum('HVAC', 'ELECTRICAL', 'PLUMBING', 'MECHANICAL', 'ELECTRONIC', 'FURNITURE', 'SECURITY', 'OTHER', name='machinetype'), nullable=False))
    op.add_column('machines', sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED', name='machinestatus'), nullable=False))
    op.add_column('machines', sa.Column('specifications', sa.Text(), nullable=True))
    op.add_column('machines', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('machines', sa.Column('warranty_expiry', sa.DateTime(), nullable=True))
    op.add_column('machines', sa.Column('last_maintenance', sa.DateTime(), nullable=True))
    op.add_column('machines', sa.Column('next_maintenance', sa.DateTime(), nullable=True))
    op.create_index('idx_machine_installation_date', 'machines', ['installation_date'], unique=False)
    op.create_index('idx_machine_next_maintenance', 'machines', ['next_maintenance'], unique=False)
    op.create_index('idx_machine_type_status', 'machines', ['machine_type', 'status'], unique=False)
    op.create_index('idx_machine_warranty_expiry', 'machines', ['warranty_expiry'], unique=False)
    op.create_index(op.f('ix_machines_installation_date'), 'machines', ['installation_date'], unique=False)
    op.create_index(op.f('ix_machines_last_maintenance'), 'machines', ['last_maintenance'], unique=False)
    op.create_index(op.f('ix_machines_machine_type'), 'machines', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machines_manufacturer'), 'machines', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_machines_next_maintenance'), 'machines', ['next_maintenance'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_index(op.f('ix_machines_warranty_expiry'), 'machines', ['warranty_expiry'], unique=False)
    op.add_column('pm_files', sa.Column('work_order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pm_files_work_order_id'), 'pm_files', ['work_order_id'], unique=False)
    op.create_foreign_key(None, 'pm_files', 'work_orders', ['work_order_id'], ['id'])
    op.add_column('topics', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('idx_topic_title_active'), table_name='topics')
    op.drop_index(op.f('ix_topics_title'), table_name='topics')
    op.create_index('idx_topic_name_active', 'topics', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.drop_column('topics', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('title', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index('idx_topic_name_active', table_name='topics')
    op.create_index(op.f('ix_topics_title'), 'topics', ['title'], unique=False)
    op.create_index(op.f('idx_topic_title_active'), 'topics', ['title', 'is_active'], unique=False)
    op.drop_column('topics', 'name')
    op.drop_constraint(None, 'pm_files', type_='foreignkey')
    op.drop_index(op.f('ix_pm_files_work_order_id'), table_name='pm_files')
    op.drop_column('pm_files', 'work_order_id')
    op.drop_index(op.f('ix_machines_warranty_expiry'), table_name='machines')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_next_maintenance'), table_name='machines')
    op.drop_index(op.f('ix_machines_manufacturer'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_last_maintenance'), table_name='machines')
    op.drop_index(op.f('ix_machines_installation_date'), table_name='machines')
    op.drop_index('idx_machine_warranty_expiry', table_name='machines')
    op.drop_index('idx_machine_type_status', table_name='machines')
    op.drop_index('idx_machine_next_maintenance', table_name='machines')
    op.drop_index('idx_machine_installation_date', table_name='machines')
    op.drop_column('machines', 'next_maintenance')
    op.drop_column('machines', 'last_maintenance')
    op.drop_column('machines', 'warranty_expiry')
    op.drop_column('machines', 'installation_date')
    op.drop_column('machines', 'specifications')
    op.drop_column('machines', 'status')
    op.drop_column('machines', 'machine_type')
    op.drop_column('machines', 'manufacturer')
    op.drop_index(op.f('ix_work_orders_work_order_type'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_title'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_started_at'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_scheduled_date'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_machine_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_is_active'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_estimated_hours'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_by_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_at'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_cost_estimate'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_completed_at'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assigned_to_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_actual_hours'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_actual_cost'), table_name='work_orders')
    op.drop_index('idx_work_order_status_type', table_name='work_orders')
    op.drop_index('idx_work_order_scheduled_date', table_name='work_orders')
    op.drop_index('idx_work_order_priority_status', table_name='work_orders')
    op.drop_index('idx_work_order_machine_status', table_name='work_orders')
    op.drop_index('idx_work_order_created_date', table_name='work_orders')
    op.drop_index('idx_work_order_completed_date', table_name='work_orders')
    op.drop_index('idx_work_order_assigned_status', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_maintenance_logs_user_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_title'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_performed_at'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_machine_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_log_type'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_labor_hours'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_created_at'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_cost'), table_name='maintenance_logs')
    op.drop_index('idx_maintenance_log_user_date', table_name='maintenance_logs')
    op.drop_index('idx_maintenance_log_type_date', table_name='maintenance_logs')
    op.drop_index('idx_maintenance_log_machine_date', table_name='maintenance_logs')
    op.drop_index('idx_maintenance_log_cost_date', table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index('idx_job_room_room', table_name='job_rooms')
    op.drop_index('idx_job_room_job', table_name='job_rooms')
    op.drop_table('job_rooms')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_title'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_unread', table_name='notifications')
    op.drop_index('idx_notification_type_date', table_name='notifications')
    op.drop_index('idx_notification_entity', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_job_user_user', table_name='job_users')
    op.drop_index('idx_job_user_job', table_name='job_users')
    op.drop_table('job_users')
    op.drop_index('idx_job_topic_topic', table_name='job_topics')
    op.drop_index('idx_job_topic_job', table_name='job_topics')
    op.drop_table('job_topics')
    op.drop_index('idx_job_property_property', table_name='job_properties')
    op.drop_index('idx_job_property_job', table_name='job_properties')
    op.drop_table('job_properties')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('idx_job_title_status', table_name='jobs')
    op.drop_index('idx_job_status_created', table_name='jobs')
    op.drop_index('idx_job_created_date', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
